language: node_js
node_js:
- '0.10'
script:
- tiddlywiki . --output . --rendertiddler $:/core/save/all index.html text/plain
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 travis-ci.key
- ssh-add travis-ci.key
- git config --global push.default simple
- git remote add deploy git@github.com:mklauber/tiddly-mathjs.git
- git checkout -b gh-pages
- git rm . -r
- git add index.html
- git push deploy
before_install:
- openssl aes-256-cbc -K $encrypted_c31c608db160_key -iv $encrypted_c31c608db160_iv
  -in travis-ci.key.enc -out travis-ci.key -d
