language: node_js
node_js:
- '0.10'

script:
- tiddlywiki . --output . --rendertiddler $:/core/save/all tmp.html text/plain

after_success:
- eval "$(ssh-agent -s)"
- chmod 600 travis-ci.key
- ssh-add travis-ci.key
- git config --global push.default simple
- git config --global user.email "your@example.com"
- git config --global user.name "Travis-CI"
- VERSION=`cat plugins/math.js/plugin.info | grep '"version"' | cut -d '"' -f 4`
- git remote add deploy git@github.com:mklauber/tiddly-mathjs.git
- git fetch deploy
- git checkout --track deploy/gh-pages
- cp tmp.html $VERSION.html
- cp tmp.html latest.html
- cp tmp.html index.html
- git add -f index.html latest.html $VERSION.html
- git commit -m "Build $VERSION"
- git push --force deploy

before_install:
- openssl aes-256-cbc -K $encrypted_c31c608db160_key -iv $encrypted_c31c608db160_iv
  -in travis-ci.key.enc -out travis-ci.key -d
