language: node_js
node_js:
 - "0.10"
script:
 - tiddlywiki . --rendertiddler $:/core/save/all index.html text/plain


after_success:
  - cat $DEPLOY_KEY > .travis/deploy_key.pem
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy git@github.com:mklauber/tiddly-mathjs.git
  - git co -b gh-pages
  - git add index.html
  - git push deploy
