language: node_js
node_js:
- '0.10'

# Decrypts the encypted SSH key used to push to github.com
before_install:
- 'if [ ! -z "${encrypted_c31c608db160_key}" ]; then openssl aes-256-cbc -K $encrypted_c31c608db160_key -iv $encrypted_c31c608db160_iv -in travis-ci.key.enc -out travis-ci.key -d; fi'

script:
- export TIDDLYWIKI_PLUGIN_PATH=$TRAVIS_BUILD_DIR/plugins/
- echo $TIDDLYWIKI_PLUGIN_PATH
- cd editions/math.js
- ../../node_modules/.bin/tiddlywiki --build

after_success:
- cd $TRAVIS_BUILD_DIR
- eval "$(ssh-agent -s)"							# 
- chmod 600 travis-ci.key							# 
- ssh-add travis-ci.key								# Setup SSH to be able to push 
- git config --global push.default simple			# to github.
- git config --global user.email "your@example.com"	# 
- git config --global user.name "Travis-CI"			# 
# Determine the version string
- VERSION=`cat plugins/math.js/plugin.info | grep '"version"' | cut -d '"' -f 4`
# Setup a git remote pointing to the source
- git remote add deploy git@github.com:mklauber/tiddly-mathjs.git
- git fetch deploy
# Tag the current commit that was used to build with the $VERSION and push it to github
- git tag -am "Version $VERSION" $VERSION
- git push --tags -f deploy # Push the tag to github
# Add the new version to the gh-pages branch
- git checkout --track deploy/gh-pages # Change to the pages branch
- cp tmp.html $VERSION.html	# Save this file under the long term version
- cp tmp.html latest.html	# Save it as the latest too.
- cp tmp.html index.html	# Save it as index.html for conviencence
- git add -f index.html latest.html $VERSION.html # add all three to git
- git commit -m "Build $VERSION" # Commit with $VERSION in the message
- git push --force deploy # Push the new version of the pages to github.

